# Generated by Django 4.2.6 on 2023-10-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('weight', models.CharField(max_length=15, verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('type', models.CharField(choices=[('eat', 'Закуски'), ('soup', 'Супы'), ('pizza', 'Пицца'), ('pasta', 'Паста'), ('sandwitch', 'Сэндвичи'), ('hot', 'Горячие блюда'), ('desert', 'Десерты'), ('drinks', 'Напитки'), ('sous', 'Соусы')], default='eat', max_length=15, verbose_name='Категория')),
            ],
        ),
    ]
