# Generated by Django 4.2.6 on 2023-10-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='main/img', verbose_name='Изображение'),
        ),
    ]
