# Generated by Django 4.2.6 on 2023-10-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('eat', 'Закуски'), ('soup', 'Супы'), ('pizza', 'Пицца'), ('pasta', 'Паста'), ('sandwitch', 'Сэндвичи'), ('hot', 'Горячие блюда'), ('desert', 'Десерты'), ('drinks', 'Напитки'), ('sous', 'Соусы'), ('salat', 'Салаты')], default='eat', max_length=15, verbose_name='Категория'),
        ),
    ]
