# Generated by Django 4.2.6 on 2023-10-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='menu_item',
        ),
    ]
